#!/bin/bash -e
echo "testing runshtrigger!!!"
echo SAMPLE_SCRIPT=res1
echo $SAMPLE_SCRIPT_IS_FORK
echo $SAMPLE_SCRIPT_IS_PULL_REQUEST
echo $SAMPLE_SCRIPT_REPO_FULL_NAME
echo $SAMPLE_SCRIPT_PULL_REQUEST_REPO_FULL_NAME
